/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CurrencyCard: typeof import('./src/components/CurrencyCard.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
  }
}
